# Generated by Django 5.1 on 2026-06-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('food_festival', 'Food Festival'), ('concert', 'Concert'), ('marathon', 'Marathon'), ('political_rally', 'Political Rally'), ('street_market', 'Street Market'), ('sports_match', 'Sports Match'), ('religious_gathering', 'Religious Gathering'), ('night_market', 'Night Market'), ('exhibition', 'Exhibition'), ('other', 'Other')], max_length=50)),
                ('expected_attendees', models.IntegerField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.FloatField()),
                ('organizer_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('compactor', 'Compactor Truck'), ('organic_hauler', 'Organic Hauler'), ('recycling_unit', 'Recycling Unit'), ('tipper', 'Tipper Truck')], max_length=30)),
                ('capacity_kg', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('deployed', 'Deployed')], default='idle', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('target_latitude', models.FloatField(blank=True, null=True)),
                ('target_longitude', models.FloatField(blank=True, null=True)),
                ('capacity_pct', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('municipality', models.CharField(choices=[('Central', 'Central Jakarta'), ('South', 'South Jakarta'), ('North', 'North Jakarta'), ('East', 'East Jakarta'), ('West', 'West Jakarta')], max_length=50)),
                ('land_use', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Coastal', 'Coastal')], max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('baseline_waste_kg_per_day', models.FloatField()),
                ('area_sqkm', models.FloatField()),
                ('population', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('assigned_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='api.fleetvehicle')),
                ('assigned_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TPSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('waste_tons', models.FloatField()),
                ('waste_type', models.CharField(choices=[('organic', 'Organic'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('mixed', 'Mixed')], max_length=20)),
                ('collection_vehicle_id', models.CharField(blank=True, max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps_records', to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('prediction_hour', models.IntegerField(default=0)),
                ('total_waste_kg', models.FloatField()),
                ('event_waste_kg', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('workers_needed', models.IntegerField()),
                ('man_hours_required', models.FloatField()),
                ('trucks_needed', models.IntegerField()),
                ('temp_bins_needed', models.IntegerField(default=0)),
                ('temp_tps_units_needed', models.IntegerField(default=0)),
                ('confidence_lower', models.FloatField()),
                ('confidence_upper', models.FloatField()),
                ('weather_condition', models.CharField(default='sunny', max_length=20)),
                ('day_type', models.CharField(default='weekday', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eventpermit')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.zone')),
            ],
            options={
                'ordering': ['prediction_date', 'prediction_hour'],
            },
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone'),
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('illegal_dump', 'Illegal Dumping'), ('collection_done', 'Collection Confirmed'), ('road_blocked', 'Road Blocked'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.driver')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='eventpermit',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.zone'),
        ),
    ]
