# Generated by Django 5.1 on 2026-06-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_routezonestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='field_reports/'),
        ),
    ]
