[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && python manage.py ensure_admin && gunicorn wasteiq.wsgi --bind 0.0.0.0:$PORT --log-file -"
restartPolicyType = "NEVER"
